### PR TITLE
more flex on type proxy

### PR DESCRIPTION
**Pull request by cbastienbaron**
'im struggle from somes hours bcz  of tor dns resolution ... :)

### CODE REVIEW

**Comment by cbastienbaron** [comment]
juste needed CURLPROXY_SOCKS5 for info

**Comment by megahertz** [comment]
You don't need to add a new variable, just pass ['curl' => [...]] as Client.get option

**Comment by cbastienbaron** [comment]
:-1:  it's annoying to change all calls from client(s), the root cause of potential pbl dns resolution is here

**Comment by megahertz** [comment]
@cbastienbaron I see no problem. Pass curl options to Client constructor, or make your own wrapper if you have a lot of calls.

**Comment by cbastienbaron** [comment]
yep i've removed this, and making my own tor middleware ... 

IMHO, it's annoying for this piece of code to force user/calls to resolve pbl done by this dns resolution.

**Comment by megahertz** [comment]
Hmm... I see no big difference between
```php
$stack->push(Middleware::tor('127.0.0.1:9050', '127.0.0.1:9051', CURLPROXY_SOCKS5));
$client = new Client(['handler' => $stack]);
```
and 
```php
$stack->push(Middleware::tor());
$client = new Client(['handler' => $stack, 'curl' => [CURLOPT_PROXYTYPE => CURLPROXY_SOCKS5]]);
```

**Comment by cbastienbaron** [comment]
if i want to instanciate X clients ( for X reasons)

```php
$client = new Client(['handler' => $stack, 'curl' => [CURLOPT_PROXYTYPE => CURLPROXY_SOCKS5]]);
$clientN = new Client(['handler' => $otherStackWithTor, 'curl' => [CURLOPT_PROXYTYPE => CURLPROXY_SOCKS5]]);
```

it's not belong to client to resolve dns pbl introduce by this middleware

**Pull request closed without merging**
